Repository AndreaGrandieri/MagicMirror-GBM, pull requests merged in 2021-04, with the labels that each got.

#182 Nodelete/msproject
  Documenti/Project Management/MagicMirror-GBM.mpp
Labels: documentation

#192 Andrea grandieri/mmm dht
  Documenti/Documenti ufficiali/Moduli/Moduli.md
  Documenti/Documenti ufficiali/Moduli/Template Documentazione Modulo.md
  docs/assets/MMM-DHT-Sensor/pin_GPIO_ref.PNG
  docs/assets/MMM-DHT-Sensor/working_module_delegateshow.jpg
  docs/assets/MMM-DHT-Sensor/working_module_ownshow.png
  docs/pages/Documentazione Moduli/MMM-DHT-Sensor/MMM-DHT-Sensor.md
  src/config/config.js
  src/modules/MMM-DHT-Sensor/.gitignore
  src/modules/MMM-DHT-Sensor/MMM-DHT-Sensor.css
  src/modules/MMM-DHT-Sensor/MMM-DHT-Sensor.js
  src/modules/MMM-DHT-Sensor/node_helper.js
  src/modules/MMM-DHT-Sensor/package.json
Labels: new-feature, urgent

#193 Gh pages main 2
  README.md
  docs/_config.yml
  docs/_includes/buttons.html
  docs/_layouts/noheader.html
  docs/assets/calendar/ICALGoogleCalendar/step1.PNG
  docs/assets/calendar/ICALGoogleCalendar/step2.PNG
  docs/assets/calendar/ICALGoogleCalendar/step3.PNG
  docs/assets/calendar/ICALGoogleCalendar/step4.PNG
  docs/assets/calendar/ICALGoogleCalendar/step5.png
  docs/assets/calendar/ICALGoogleCalendar/step6.PNG
  docs/assets/calendar/ICALGoogleCalendar/step7.PNG
  docs/assets/calendar/ICALGoogleCalendar/step7_2.PNG
  docs/assets/calendar/ICALGoogleCalendar/step8.PNG
  docs/assets/calendar/ICALGoogleCalendar/step9.PNG
  docs/assets/css/style.scss
  docs/assets/newsfeed/NFScreenshot.png
  docs/index.md
  docs/js/main.js
  docs/pages/ArchivioBMC.md
  docs/pages/ArchivioDocumentiDeiRequisiti.md
  docs/pages/DocumentazioneModuli/MMM-AirQuality/MMM-AirQuality.md
  docs/pages/DocumentazioneModuli/MMM-DHT-Sensor/MMM-DHT-Sensor.md
  docs/pages/DocumentazioneModuli/MMM-Online-State/MMM-Online-State.md
  docs/pages/DocumentazioneModuli/MMM-Screencast/MMM-Screencast.md
  docs/pages/DocumentazioneModuli/MMM-ip/MMM-ip.md
  docs/pages/DocumentazioneModuli/calendar/calendar.md
  docs/pages/DocumentazioneModuli/clock/clock.md
  docs/pages/DocumentazioneModuli/newsfeed/newsfeed.md
  docs/pages/DocumentazioneModuli/weather/weather.md
  docs/pages/DocumentazioneModuli/weatherforecast/weatherforecast.md
  test/_config (outdated).yml
Labels: bug, documentation, epic, modify-feature, new-feature, urgent

#196 Mmm av stock
  Documenti/Documenti ufficiali/Versione Riserva Documento Modulo MMM-AVStock/MMM-AVStock.md
  docs/assets/MMM-AVStock/chartType_candlestick.PNG
  docs/assets/MMM-AVStock/chartType_ohlc.PNG
  docs/assets/MMM-AVStock/mode_grid.PNG
  docs/assets/MMM-AVStock/mode_table_chartType_line.PNG
  docs/assets/MMM-AVStock/mode_ticker.gif
  docs/assets/MMM-AVStock/step2.PNG
  docs/assets/MMM-AVStock/step3.PNG
  docs/assets/MMM-AVStock/step4.png
  docs/pages/DocumentazioneModuli/MMM-AVStock/MMM-AVStock.md
  src/config/config.js
  src/modules/MMM-AVStock/.gitignore
  src/modules/MMM-AVStock/.gitpod.yml
  src/modules/MMM-AVStock/.theia/launch.json
  src/modules/MMM-AVStock/MMM-AVStock.css
  src/modules/MMM-AVStock/MMM-AVStock.js
  src/modules/MMM-AVStock/node_helper.js
  src/modules/MMM-AVStock/package.json
Labels: new-feature, urgent

#199 Documento dei requisiti4.0
  Documenti/Documenti ufficiali/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v4.0/DocumentoDeiRequisitiConfigurazionePrivata-v4.0.md
  Documenti/Documenti ufficiali/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v4.0/main.tex
  Documenti/Documenti ufficiali/Moduli/Moduli.md
  docs/assets/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v4.0/DocumentoDeiRequisitiConfigurazionePrivata_v4_0_.pdf
  docs/pages/ArchivioDocumentiDeiRequisiti.md
Labels: documentation

#201 Gh pages main 2
  README.md
  docs/README.md
  docs/pages/DocumentazioneModuli/MMM-AVStock/MMM-AVStock.md
  docs/pages/DocumentazioneModuli/MMM-DHT-Sensor/MMM-DHT-Sensor.md
  docs/pages/DocumentazioneModuli/MMM-MD/MMM-MD.md
Labels: documentation, epic, new-feature, urgent

#203 Andrea grandieri/cito emulazione
  Documenti/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v1.0/DocumentoDeiRequisitiConfigurazionePrivata-v1.0.md
  Documenti/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v2.0/DocumentoDeiRequisitiConfigurazionePrivata-v2.0.md
  Documenti/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v2.0/main.tex
  Documenti/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v3.0/DocumentoDeiRequisitiConfigurazionePrivata-v3.0.md
  Documenti/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v3.0/main.tex
  Documenti/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v4.0/DocumentoDeiRequisitiConfigurazionePrivata-v4.0.md
  Documenti/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v4.0/main.tex
  Documenti/GitHub Pages Docs/GitHub Pages All Badges.md
  Documenti/GitHub Pages Docs/Template GitHub Pages.md
  Documenti/Istruzione per Testing/instruction.md
  Documenti/Kick-Off Questions.md
  Documenti/Moduli/DataTypesJS.PNG
  Documenti/Moduli/IMPORTANTE-gestione-dir-implementazione-moduli.md
  Documenti/Moduli/LinkStorming.md
  Documenti/Moduli/Moduli.md
  Documenti/Moduli/Template Documentazione Modulo.md
  Documenti/Moduli/outdated/Moduli Mancanti (outdated).md
  Documenti/Moduli/outdated/integrazione (outdated).md
  Documenti/Ruoli.md
  Documenti/Versione Riserva Documento Modulo MMM-AVStock/MMM-AVStock.md
  Documenti/ideaimpresa/Dettagli operativi concorso ideaimpresa.md
  Documenti/ideaimpresa/Meetings Log ideaimpresa.md
  docs/README.md
  docs/pages/ArchivioBMC.md
  docs/pages/ArchivioDocumentiDeiRequisiti.md
  docs/pages/DocumentazioneModuli/MMM-AVStock/MMM-AVStock.md
  docs/pages/DocumentazioneModuli/MMM-AirQuality/MMM-AirQuality.md
  docs/pages/DocumentazioneModuli/MMM-DHT-Sensor/MMM-DHT-Sensor.md
  docs/pages/DocumentazioneModuli/MMM-MD/MMM-MD.md
  docs/pages/DocumentazioneModuli/MMM-Online-State/MMM-Online-State.md
  docs/pages/DocumentazioneModuli/MMM-Screencast/MMM-Screencast.md
  docs/pages/DocumentazioneModuli/MMM-ip/MMM-ip.md
  docs/pages/DocumentazioneModuli/calendar/calendar.md
  docs/pages/DocumentazioneModuli/clock/clock.md
  docs/pages/DocumentazioneModuli/newsfeed/newsfeed.md
  docs/pages/DocumentazioneModuli/weather/weather.md
  docs/pages/DocumentazioneModuli/weatherforecast/weatherforecast.md
  docs/pages/Emulazione.md
Labels: documentation, epic, modify-feature, urgent

#204 Gh pages main 2
  docs/pages/Emulazione.md
Labels: documentation, modify-feature, new-feature, urgent

#208 Manu2110/mmm mail fx
  docs/assets/MMM-Mail/screenshot.PNG
  docs/assets/MMM-Mail/step1.png
  docs/assets/MMM-Mail/step2.png
  docs/assets/MMM-Mail/step3.png
  docs/pages/DocumentazioneModuli/MMM-Mail/MMM-Mail.md
  src/config/config.js
  src/modules/MMM-Mail/MMM-Mail.js
  src/modules/MMM-Mail/email.css
  src/modules/MMM-Mail/node_helper.js
  src/modules/MMM-Mail/package.json
Labels: new-feature

#210 Gh pages main 2
  docs/README.md
  docs/pages/DocumentazioneModuli/MMM-PIR-Sensor/MMM-PIR-Sensor.md
Labels: documentation, new-feature, urgent

#211 Documento dei requisiti ver. 6.0 parziale
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisiti-v6.0/DocumentoDeiRequisiti-v6.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisiti-v6.0/main.tex
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v1.0/DocumentoDeiRequisitiConfigurazionePrivata-v1.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v2.0/DocumentoDeiRequisitiConfigurazionePrivata-v2.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v2.0/main.tex
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v3.0/DocumentoDeiRequisitiConfigurazionePrivata-v3.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v3.0/main.tex
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v4.0/DocumentoDeiRequisitiConfigurazionePrivata-v4.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v4.0/main.tex
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v5.0/DocumentoDeiRequisitiConfigurazionePrivata-v5.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v5.0/main.tex
  docs/assets/DocumentoDeiRequisiti/DocumentoDeiRequisiti-v6.0/DocumentoDeiRequisiti_v6_0_.pdf
  docs/pages/ArchivioDocumentiDeiRequisiti.md
Labels: documentation

#215 Andrea grandieri/mmm mail fix definitivo
  docs/pages/DocumentazioneModuli/MMM-Mail/MMM-Mail.md
  src/config/config.js
  src/modules/MMM-Mail/node_helper.js
Labels: bug, modify-feature, new-feature, urgent

#218 Trasferita documentazione interna in un archivio privato al team este…
  Documenti/.gitinclude
  Documenti/Bozze/.gitinclude
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisiti-v6.0/DocumentoDeiRequisiti-v6.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisiti-v6.0/main.tex
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v1.0/DocumentoDeiRequisitiConfigurazionePrivata-v1.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v2.0/DocumentoDeiRequisitiConfigurazionePrivata-v2.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v2.0/main.tex
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v3.0/DocumentoDeiRequisitiConfigurazionePrivata-v3.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v3.0/main.tex
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v4.0/DocumentoDeiRequisitiConfigurazionePrivata-v4.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v4.0/main.tex
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v5.0/DocumentoDeiRequisitiConfigurazionePrivata-v5.0.md
  Documenti/DocumentoDeiRequisiti/DocumentoDeiRequisitiConfigurazionePrivata-v5.0/main.tex
  Documenti/GitHub Pages Docs/GitHub Pages All Badges.md
  Documenti/GitHub Pages Docs/Template GitHub Pages.md
  Documenti/Istruzione per Testing/instruction.md
  Documenti/Kick-Off Questions.md
  Documenti/Meetings Log/.gitinclude
  Documenti/Meetings Log/Integrazione05032021 (risolto).md
  Documenti/Meetings Log/Meeting del 10.03.2021.md
  Documenti/Meetings Log/Meeting del 23.03.2021.md
  Documenti/Meetings Log/Meetings Log.md
  Documenti/Meetings Log/meeting 23 febbraio 2021
  Documenti/Moduli/DataTypesJS.PNG
  Documenti/Moduli/IMPORTANTE-gestione-dir-implementazione-moduli.md
  Documenti/Moduli/LinkStorming.md
  Documenti/Moduli/Moduli.md
  Documenti/Moduli/Template Documentazione Modulo.md
  Documenti/Moduli/outdated/Moduli Mancanti (outdated).md
  Documenti/Moduli/outdated/integrazione (outdated).md
  Documenti/Project Management/.gitinclude
  Documenti/Project Management/MagicMirror-GBM.mpp
  Documenti/Project Management/resources/Pianificazione Temporale Parziale Implementazione Moduli_26.02.2021.PNG
  Documenti/Ruoli.md
  Documenti/Versione Riserva Documento Modulo MMM-AVStock/MMM-AVStock.md
  test/.gitinclude
  test/_config (outdated).yml
  test/node2.js.yml
  test/package (outdated).json
Labels: Richieste Prof, big-changer, documentation, epic, modify-feature, urgent

#223 Documento dei requisiti v7.0 e documento generico dei casi d'uso
  docs/assets/DocumentoDeiRequisiti/DocumentoDeiRequisiti-v7.0/DocumentoDeiRequsiti_v7_0 .pdf
  docs/assets/UseCaseDiagrams/GenericUseCaseDiagram.pdf
Labels: documentation, new-feature

#225 Merge documentazioni varie
  docs/README.md
  docs/assets/UMLComponentDiagram/UML_Component_Diagram_v1.0_fitToPage_MagicMirror-GBM.pdf
  docs/pages/ArchivioUMLComponentDiagram.md
Labels: documentation, urgent

#234 Fix molto urgenti e incasinati
  src/ipdashboard/index.php
  src/ipdashboard/php/WIFIConfigurator.php
  src/ipdashboard/php/doAudioConfigurator.php
  src/ipdashboard/php/doWIFIConfigurator.php
  src/ipdashboard/php/redirect.php
Labels: critical, modify-feature, urgent

#237 Documento dei casi d'uso generico FINALE
  docs/assets/UseCaseDiagrams/GenericUseCaseDiagram-v1.0.pdf
  docs/assets/UseCaseDiagrams/GenericUseCaseDiagram-v2.0.pdf
Labels: documentation

#242 Documento dei requisiti finale
  docs/assets/DocumentoDeiRequisiti/DocumentoDeiRequisiti-v8.0/DocumentoDeiRequisiti_v8_0.pdf
Labels: documentation

#240 Documento dei casi d'uso specifico
  docs/assets/UseCaseDiagrams/Specific/SpecificUseCaseDiagram-v1.0_MagicMirror-GBM.pdf
  docs/pages/UseCaseDiagrams/ArchivioSpecificUseCaseDiagram.md
Labels: documentation

#247 V2.0 documento casi d'uso specifico
  docs/assets/UseCaseDiagrams/Specific/SpecificUseCaseDiagram_v2.0_MagicMirror-GBM.pdf
Labels: documentation

#251 Andrea grandieri/urgente/interfaccia ip mmm md
  docs/assets/ProgettazioneDatabase_settings/v2.0/DB_settings-Progettazione_Fisica_v2.0.pdf
  docs/assets/ProgettazioneDatabase_settings/v2.0/php/Costruttore_v2.0.php
  docs/pages/ProgettazioneDatabase_settings/ProgettazioneDatabase_settings.md
  docs/pages/ProgettazioneDatabase_settings/v2.0/DB_settings-Progettazione_Fisica_v2.0.md
  src/ipdashboard/php/MMM-MD-ContentEditor.php
  src/ipdashboard/php/doRipristinaDatabase.php
  src/ipdashboard/php/doRipristinaDatabaseBackdoor.php
  src/ipdashboard/php/index.php
  src/ipdashboard/php/saveMMM-MD-ContentEditor.php
  src/ipdashboard/utils/editor.js
  test
Labels: big-changer, documentation, new-feature, urgent

#252 feature sospesa e resa stale all'utente
  src/ipdashboard/php/aggiornamentoSoftware.php.stale
  src/ipdashboard/php/doAggiornamentoSoftware.php.stale
  src/ipdashboard/php/index.php
Labels: modify-feature, urgent
