Repository AndreaGrandieri/MagicMirror-GBM, pull requests merged in 2021-02, with the labels that each got.

#16 Nodelete/meetings log
  Documenti/Meetings Log/Meetings Log.md
Labels: documentation

#12 Rename ruoli.md to Ruoli.md
  Documenti/Documenti ufficiali/Ruoli.md
Labels: documentation

#20 moved MPP file
  Documenti/Project Management/MagicMirror-GBM.mpp
Labels: documentation

#22 Update README.md
  README.md
Labels: documentation

#24 Update Meetings Log.md
  Documenti/Meetings Log/Meetings Log.md
Labels: documentation

#32 Documento dei requisiti
  Documenti/Bozze/Documento dei Requisiti.md
Labels: documentation, new-feature

#31 Update MagicMirror-GBM.mpp
  Documenti/Project Management/MagicMirror-GBM.mpp
Labels: documentation

#27 Aggiornamento "Meetings Log" e promozione "Kick-Off Questions"
  Documenti/Documenti ufficiali/Kick-Off Questions.md
  Documenti/Meetings Log/Meetings Log.md
Labels: documentation

#37 Update MagicMirror-GBM.mpp
  Documenti/Project Management/MagicMirror-GBM.mpp
Labels: documentation, modify-feature

#36 Aggiunti ultimi due meeting
  Documenti/Meetings Log/Meetings Log.md
Labels: documentation, modify-feature

#35 Creazione file per bozza tabella moduli
  Documenti/Bozze/Moduli.md
Labels: documentation, new-feature

#39 Aggiunto log meeting del 18/02/2021
  Documenti/Meetings Log/Meetings Log.md
Labels: documentation, modify-feature

#38 Update MagicMirror-GBM.mpp
  Documenti/Project Management/MagicMirror-GBM.mpp
Labels: documentation, modify-feature

#45 Create LICENSE
  LICENSE
Labels: documentation, new-feature

#69 Create Template GitHub Pages.md
  Documenti/Documenti ufficiali/Template GitHub Pages.md
Labels: documentation, new-feature

#67 Delete .gitinclude
  docs/.gitinclude
Labels: modify-feature

#65 Src moduli preparazione dir
  src/IMPORTANTE-gestione-dir.md
  src/Moduli/.gitinclude
Labels: documentation, new-feature

#64 Update MagicMirror-GBM.mpp
  Documenti/Project Management/MagicMirror-GBM.mpp
Labels: documentation

#46 meeting 23 febbraio 2021
  Documenti/Meetings Log/meeting 23 febbraio 2021
Labels: documentation

#43 Bozza moduli
  Documenti/Bozze/Documento dei Requisiti.md
  Documenti/Bozze/Moduli.md
  Documenti/Bozze/Moduli/LinkStorming.md
  Documenti/Bozze/Moduli/Moduli.md
  Documenti/Bozze/Moduli/outdated/Moduli Mancanti (outdated).md
  Documenti/Bozze/Moduli/outdated/integrazione (outdated).md
Labels: documentation, modify-feature

#70 Create GitHub Pages All Badges.md
  Documenti/Documenti ufficiali/GitHub Pages All Badges.md
Labels: documentation

#73 Create package.json
  package.json
Labels: invalid, question

#77 Moduli classificazione apikey
  Documenti/Bozze/Moduli/Moduli.md
Labels: documentation

#78 Nodelete/msproject
  Documenti/Project Management/MagicMirror-GBM.mpp
  Documenti/Project Management/resources/Pianificazione Temporale Parziale Implementazione Moduli_26.02.2021.PNG
Labels: documentation
