Repository AndreaGrandieri/MagicMirror-GBM, pull requests merged in 2021-03, with the labels that each got.

#79 Aggiunta pianificazione temporale per attività: "Implementazione OS"
  Documenti/Project Management/MagicMirror-GBM.mpp
Labels: documentation

#85 Aggiunto log meeting del 27/02/2021
  Documenti/Meetings Log/Meetings Log.md
Labels: documentation

#88 Aggiunti badge in "README.md"
  README.md
Labels: documentation

#87 Template documentazione moduli
  Documenti/Documenti ufficiali/Moduli/DataTypesJS.PNG
  Documenti/Documenti ufficiali/Moduli/LinkStorming.md
  Documenti/Documenti ufficiali/Moduli/Moduli.md
  Documenti/Documenti ufficiali/Moduli/Template Documentazione Modulo.md
  Documenti/Documenti ufficiali/Moduli/outdated/Moduli Mancanti (outdated).md
  Documenti/Documenti ufficiali/Moduli/outdated/integrazione (outdated).md
  src/config/config.js
  src/modules/MMM-AirQuality/MMM-AirQuality.md
  src/modules/MMM-AirQuality/resources/loading_air_quality_index_hang.PNG
Labels: documentation, urgent

#92 Aggiornamento struttura dir "Documenti Ufficiali" e aggiornamento ist…
  Documenti/Documenti ufficiali/.gitinclude
  Documenti/Documenti ufficiali/GitHub Pages Docs/GitHub Pages All Badges.md
  Documenti/Documenti ufficiali/GitHub Pages Docs/Template GitHub Pages.md
  Documenti/Documenti ufficiali/Istruzione per Testing/instruction.md
  Documenti/Documenti ufficiali/Moduli/IMPORTANTE-gestione-dir-implementazione-moduli.md
Labels: documentation, urgent

#94 Aggiunto log meeting del 03/03/2021
  Documenti/Meetings Log/Meetings Log.md
Labels: documentation

#97 Update modulo clock
  src/modules/default/clock/README.md
  src/modules/default/clock/clock.md
  src/modules/default/clock/resources/clock.png
Labels: documentation, new-feature

#98 Correzione badge dipendenze
  README.md
Labels: documentation

#95 Create Integrazione05032021.md
  Documenti/Bozze/Integrazione05032021.md
Labels: documentation, new-feature, question

#105 Rimosso modulo default compliments
  src/config/config.js
Labels: modify-feature, new-feature

#103 Andrea grandieri/mmm online state
  Documenti/Documenti ufficiali/Moduli/Moduli.md
  src/config/config.js
  src/modules/MMM-Online-State/MMM-Online-State.js
  src/modules/MMM-Online-State/MMM-Online-State.md
  src/modules/MMM-Online-State/resources/connection_is_not_ok.PNG
  src/modules/MMM-Online-State/resources/connection_is_ok.PNG
Labels: new-feature

#104 Aggiunta milestone MMM-Online-State. Necessaria revisione intera sche…
  Documenti/Project Management/MagicMirror-GBM.mpp
Labels: documentation

#112 Andrea grandieri/weather forecast module
  src/config/config.js
  src/modules/default/weather/README.md
  src/modules/default/weather/resources/search_bar_getlocationID.PNG
  src/modules/default/weather/resources/search_bar_used_getlocationID.PNG
  src/modules/default/weather/resources/url_gotlocationID.PNG
  src/modules/default/weather/resources/working_module.PNG
  src/modules/default/weather/weather.md
  src/modules/default/weatherforecast/README.md
  src/modules/default/weatherforecast/resources/working_module.PNG
  src/modules/default/weatherforecast/weatherforecast.md
Labels: new-feature

#107 Modulo Weather richiede una API KEY!
  Documenti/Documenti ufficiali/Moduli/Moduli.md
Labels: documentation

#106 Andrea grandieri/mmm screencast light
  src/config/config.js
  src/modules/MMM-Screencast/.gitignore
  src/modules/MMM-Screencast/DialServer.js
  src/modules/MMM-Screencast/MMM-Screencast.js
  src/modules/MMM-Screencast/MMM-Screencast.md
  src/modules/MMM-Screencast/app.js
  src/modules/MMM-Screencast/constants.js
  src/modules/MMM-Screencast/injector.js
  src/modules/MMM-Screencast/ipc.js
  src/modules/MMM-Screencast/node_helper.js
  src/modules/MMM-Screencast/package.json
  src/modules/MMM-Screencast/resources/cast_magicmirror.jpg
  src/modules/MMM-Screencast/resources/cast_smartdevice.png
  src/modules/MMM-Screencast/screenshots/screenshot.png
  src/modules/MMM-Screencast/screenshots/screenshot1.png
  src/modules/MMM-Screencast/screenshots/screenshot2.jpg
Labels: new-feature

#114 Rimossa duplicazione modulo MMM-Online-State nel file config.js
  src/config/config.js
Labels: bug, modify-feature

#117 Update README.md
  README.md
Labels: documentation

#118 Update module MMM-StopwatchTimer
  src/config/config.js
  src/modules/MMM-StopwatchTimer/MMM-StopwatchTimer.js
  src/modules/MMM-StopwatchTimer/MMM-StopwatchTimer.md
  src/modules/MMM-StopwatchTimer/popup.css
  src/modules/MMM-StopwatchTimer/resources/Timer.gif
Labels: modify-feature, new-feature

#125 Spostato Integrazione05032021 in quanto risolto
  Documenti/Meetings Log/Integrazione05032021 (risolto).md
Labels: documentation, urgent

#133 Documento dei requisiti
  Documenti/Bozze/DocumentoDeiRequisitiConfigurazionePrivata v2.0.md
  Documenti/Documenti ufficiali/DocumentoDeiRequisitiConfigurazionePrivata v2.0/DocumentoDeiRequisitiConfigurazionePrivata_v2_0_.pdf
  Documenti/Documenti ufficiali/DocumentoDeiRequisitiConfigurazionePrivata v2.0/main.tex
Labels: documentation

#132 Nodelete/meetings log
  Documenti/Meetings Log/Integrazione05032021 (risolto).md
  Documenti/Meetings Log/Meeting del 10.03.2021.md
  Documenti/Meetings Log/Meetings Log.md
  Documenti/ideaimpresa/Dettagli operativi concorso ideaimpresa.md
  Documenti/ideaimpresa/Meetings Log ideaimpresa.md
Labels: documentation, urgent

#136 Andrea grandieri/mmm ip
  Documenti/Documenti ufficiali/Moduli/Moduli.md
  src/config/config.js
  src/modules/MMM-ip/.codeclimate.yml
  src/modules/MMM-ip/.editorconfig
  src/modules/MMM-ip/.eslintignore
  src/modules/MMM-ip/.eslintrc
  src/modules/MMM-ip/.gitignore
  src/modules/MMM-ip/.mdlrc
  src/modules/MMM-ip/.travis.yml
  src/modules/MMM-ip/MMM-ip.js
  src/modules/MMM-ip/MMM-ip.md
  src/modules/MMM-ip/jsdoc.json
  src/modules/MMM-ip/netstat mmm-ip doc
  src/modules/MMM-ip/node_helper.js
  src/modules/MMM-ip/package-lock.json
  src/modules/MMM-ip/package.json
  src/modules/MMM-ip/resources/working_module.PNG
  src/modules/MMM-ip/templates/HelpModal.njk
  src/modules/MMM-ip/templates/InterfaceModal.njk
  src/modules/MMM-ip/templates/MMM-ip.njk
  src/modules/MMM-ip/translations/de.json
  src/modules/MMM-ip/translations/en.json
Labels: new-feature, urgent

#139 Nodelete/msproject
  Documenti/Project Management/MagicMirror-GBM.mpp
Labels: documentation

#151 Nodelete/meetings log
  Documenti/Meetings Log/Meetings Log.md
Labels: documentation, urgent

#152 Andrea grandieri/mmm air quality
  Documenti/Documenti ufficiali/Moduli/Template Documentazione Modulo.md
  src/modules/MMM-AirQuality/MMM-AirQuality.md
  src/modules/MMM-Online-State/MMM-Online-State.md
  src/modules/MMM-Screencast/MMM-Screencast.md
  src/modules/MMM-StopwatchTimer/MMM-StopwatchTimer.md
  src/modules/MMM-ip/MMM-ip.md
  src/modules/default/clock/clock.md
  src/modules/default/weather/weather.md
  src/modules/default/weatherforecast/weatherforecast.md
Labels: modify-feature, urgent

#153 Andrea grandieri/mmm online state 2
  src/modules/MMM-Online-State/MMM-Online-State.md
Labels: modify-feature, urgent

#155 Andrea grandieri/mmm screencast 2
  Documenti/Documenti ufficiali/Moduli/Template Documentazione Modulo.md
  src/modules/MMM-Screencast/MMM-Screencast.md
Labels: modify-feature, urgent

#156 Rimossi commenti NON ammessi in alcuni frammenti JSON nei documenti p…
  src/modules/MMM-AirQuality/MMM-AirQuality.md
  src/modules/MMM-Online-State/MMM-Online-State.md
  src/modules/MMM-Screencast/MMM-Screencast.md
  src/modules/default/clock/clock.md
Labels: documentation, modify-feature, urgent

#158 Andrea grandieri/calendar
  src/modules/default/calendar/README.md
  src/modules/default/calendar/calendar.md
  src/modules/default/calendar/resources/ICAL Google Calendar/step1.PNG
  src/modules/default/calendar/resources/ICAL Google Calendar/step2.PNG
  src/modules/default/calendar/resources/ICAL Google Calendar/step3.PNG
  src/modules/default/calendar/resources/ICAL Google Calendar/step4.PNG
  src/modules/default/calendar/resources/ICAL Google Calendar/step5.png
  src/modules/default/calendar/resources/ICAL Google Calendar/step6.PNG
  src/modules/default/calendar/resources/ICAL Google Calendar/step7.PNG
  src/modules/default/calendar/resources/ICAL Google Calendar/step7_2.PNG
  src/modules/default/calendar/resources/ICAL Google Calendar/step8.PNG
  src/modules/default/calendar/resources/ICAL Google Calendar/step9.PNG
  src/modules/default/calendar/resources/absolute_timeFormat.PNG
  src/modules/default/calendar/resources/rel/rel1.PNG
  src/modules/default/calendar/resources/rel/rel1_1.PNG
  src/modules/default/calendar/resources/rel/rel2.PNG
  src/modules/default/calendar/resources/rel/rel2_1.PNG
  src/modules/default/calendar/resources/rel/rel3.PNG
  src/modules/default/calendar/resources/rel/rel3_1.PNG
  src/modules/default/calendar/resources/rel/rel4.PNG
  src/modules/default/calendar/resources/rel/rel4_1.PNG
  src/modules/default/calendar/resources/rel/rel5.PNG
  src/modules/default/calendar/resources/rel/rel5_1.PNG
  src/modules/default/calendar/resources/rel/rel6.PNG
  src/modules/default/calendar/resources/rel/rel6_1.PNG
  src/modules/default/calendar/resources/rel/rel7.PNG
  src/modules/default/calendar/resources/rel/rel7_1.PNG
  src/modules/default/calendar/resources/relative_timeFormat.PNG
  src/modules/default/calendar/resources/working_module.PNG
Labels: new-feature, urgent

#160 Aggiunta sezione notifiche
  src/modules/default/clock/clock.md
Labels: modify-feature, urgent

#161 Completata sezione notifiche
  src/modules/MMM-StopwatchTimer/MMM-StopwatchTimer.md
  src/modules/MMM-StopwatchTimer/old_Notifiche.md
Labels: modify-feature, urgent

#162 Sezione Notifiche completata per modulo Weather Module
  src/modules/default/weather/weather.md
  src/modules/default/weatherforecast/weatherforecast.md
Labels: modify-feature, urgent

#163 Andrea grandieri/mmm ip
  src/modules/MMM-ip/MMM-ip.md
Labels: modify-feature, urgent

#165 Creata cartella "assets". Definizione:
  assets/MMM-AirQuality/MMM-AirQuality_correct_workflow.PNG
  assets/MMM-AirQuality/loading_air_quality_index_hang.PNG
  assets/MMM-Online-State/connection_is_not_ok.PNG
  assets/MMM-Online-State/connection_is_ok.PNG
  assets/MMM-Screencast/cast_magicmirror.jpg
  assets/MMM-Screencast/cast_smartdevice.png
  assets/MMM-StopwatchTimer/Timer.gif
  assets/MMM-ip/working_module.PNG
  assets/calendar/ICAL Google Calendar/step1.PNG
  assets/calendar/ICAL Google Calendar/step2.PNG
  assets/calendar/ICAL Google Calendar/step3.PNG
  assets/calendar/ICAL Google Calendar/step4.PNG
  assets/calendar/ICAL Google Calendar/step5.png
  assets/calendar/ICAL Google Calendar/step6.PNG
  assets/calendar/ICAL Google Calendar/step7.PNG
  assets/calendar/ICAL Google Calendar/step7_2.PNG
  assets/calendar/ICAL Google Calendar/step8.PNG
  assets/calendar/ICAL Google Calendar/step9.PNG
  assets/calendar/absolute_timeFormat.PNG
  assets/calendar/rel/rel1.PNG
  assets/calendar/rel/rel1_1.PNG
  assets/calendar/rel/rel2.PNG
  assets/calendar/rel/rel2_1.PNG
  assets/calendar/rel/rel3.PNG
  assets/calendar/rel/rel3_1.PNG
  assets/calendar/rel/rel4.PNG
  assets/calendar/rel/rel4_1.PNG
  assets/calendar/rel/rel5.PNG
  assets/calendar/rel/rel5_1.PNG
  assets/calendar/rel/rel6.PNG
  assets/calendar/rel/rel6_1.PNG
  assets/calendar/rel/rel7.PNG
  assets/calendar/rel/rel7_1.PNG
  assets/calendar/relative_timeFormat.PNG
  assets/calendar/working_module.PNG
  assets/clock/clock.png
  assets/weather/search_bar_getlocationID.PNG
  assets/weather/search_bar_used_getlocationID.PNG
  assets/weather/url_gotlocationID.PNG
  assets/weather/working_module.PNG
  assets/weatherforecast/working_module.PNG
  resources/.gitinclude
  src/modules/MMM-Screencast/screenshots/screenshot.png
  src/modules/MMM-Screencast/screenshots/screenshot1.png
  src/modules/MMM-Screencast/screenshots/screenshot2.jpg
Labels: big-changer, modify-feature, urgent

#166 Create calendar.md
  pages/modules/calendar.md
Labels: documentation

#167 Nodelete/gh pages main
  calendar.md
Labels: bug, documentation, urgent

#168 FORTE transizione a "main -> /docs/" per build di GitHub Pages
  calendar.md
  docs/_config.yml
  docs/_includes/buttons.html
  docs/assets/MMM-AirQuality/MMM-AirQuality_correct_workflow.PNG
  docs/assets/MMM-AirQuality/loading_air_quality_index_hang.PNG
  docs/assets/MMM-Online-State/connection_is_not_ok.PNG
  docs/assets/MMM-Online-State/connection_is_ok.PNG
  docs/assets/MMM-Screencast/cast_magicmirror.jpg
  docs/assets/MMM-Screencast/cast_smartdevice.png
  docs/assets/MMM-StopwatchTimer/Timer.gif
  docs/assets/MMM-ip/working_module.PNG
  docs/assets/calendar/ICAL Google Calendar/step1.PNG
  docs/assets/calendar/ICAL Google Calendar/step2.PNG
  docs/assets/calendar/ICAL Google Calendar/step3.PNG
  docs/assets/calendar/ICAL Google Calendar/step4.PNG
  docs/assets/calendar/ICAL Google Calendar/step5.png
  docs/assets/calendar/ICAL Google Calendar/step6.PNG
  docs/assets/calendar/ICAL Google Calendar/step7.PNG
  docs/assets/calendar/ICAL Google Calendar/step7_2.PNG
  docs/assets/calendar/ICAL Google Calendar/step8.PNG
  docs/assets/calendar/ICAL Google Calendar/step9.PNG
  docs/assets/calendar/absolute_timeFormat.PNG
  docs/assets/calendar/rel/rel1.PNG
  docs/assets/calendar/rel/rel1_1.PNG
  docs/assets/calendar/rel/rel2.PNG
  docs/assets/calendar/rel/rel2_1.PNG
  docs/assets/calendar/rel/rel3.PNG
  docs/assets/calendar/rel/rel3_1.PNG
  docs/assets/calendar/rel/rel4.PNG
  docs/assets/calendar/rel/rel4_1.PNG
  docs/assets/calendar/rel/rel5.PNG
  docs/assets/calendar/rel/rel5_1.PNG
  docs/assets/calendar/rel/rel6.PNG
  docs/assets/calendar/rel/rel6_1.PNG
  docs/assets/calendar/rel/rel7.PNG
  docs/assets/calendar/rel/rel7_1.PNG
  docs/assets/calendar/relative_timeFormat.PNG
  docs/assets/calendar/working_module.PNG
  docs/assets/clock/clock.png
  docs/assets/weather/search_bar_getlocationID.PNG
  docs/assets/weather/search_bar_used_getlocationID.PNG
  docs/assets/weather/url_gotlocationID.PNG
  docs/assets/weather/working_module.PNG
  docs/assets/weatherforecast/working_module.PNG
  docs/index.md
  docs/js/main.js
  docs/pages/Documentazione Moduli/MMM-AirQuality/MMM-AirQuality.md
  docs/pages/Documentazione Moduli/MMM-Online-State/MMM-Online-State.md
  docs/pages/Documentazione Moduli/MMM-Screencast/MMM-Screencast.md
  docs/pages/Documentazione Moduli/MMM-StopwatchTimer/MMM-StopwatchTimer.md
  docs/pages/Documentazione Moduli/MMM-ip/MMM-ip.md
  docs/pages/Documentazione Moduli/calendar/calendar.md
  docs/pages/Documentazione Moduli/clock/clock.md
  docs/pages/Documentazione Moduli/weather/weather.md
  docs/pages/Documentazione Moduli/weatherforecast/weatherforecast.md
  src/modules/default/calendar/resources/test.PNG
Labels: big-changer, documentation, modify-feature, urgent

#169 Aggiunto modulo News Feed
  docs/assets/NewsFeed/NFScreenshot.png
  docs/pages/Documentazione Moduli/News Feed/NewsFeed.md
  src/config/config.js
Labels: new-feature

#174 Documentati aggiornamenti da molteplici meeting (+con azienda)
  Documenti/Meetings Log/Meeting del 23.03.2021.md
  Documenti/Meetings Log/Meetings Log.md
Labels: documentation, urgent

#175 Rimossi tutti i riferimenti trovati al modulo MMM-StopwatchTimer, il …
  Documenti/Documenti ufficiali/Moduli/Moduli.md
  Documenti/Project Management/MagicMirror-GBM.mpp
  docs/assets/MMM-StopwatchTimer/Timer.gif
  docs/pages/Documentazione Moduli/MMM-StopwatchTimer/MMM-StopwatchTimer.md
  src/config/config.js
  src/modules/MMM-StopwatchTimer/MMM-StopwatchTimer.js
  src/modules/MMM-StopwatchTimer/old_Notifiche.md
  src/modules/MMM-StopwatchTimer/popup.css
Labels: documentation, modify-feature, urgent

#177 Rimozione tutti i riferimenti agli orfani individuati (eccetto docume…
  Documenti/Documenti ufficiali/Moduli/Moduli.md
  Documenti/Project Management/MagicMirror-GBM.mpp
Labels: documentation, modify-feature, urgent

#179 Nodelete/gh pages main
  Documenti/Documenti ufficiali/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v1.0/DocumentoDeiRequisitiConfigurazionePrivata-v1.0.md
  Documenti/Documenti ufficiali/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v2.0/DocumentoDeiRequisitiConfigurazionePrivata-v2.0.md
  Documenti/Documenti ufficiali/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v2.0/main.tex
  docs/_layouts/noheader.html
  docs/assets/DocumentoDeiRequisitiConfigurazionePrivata/DocumentoDeiRequisitiConfigurazionePrivata-v2.0/DocumentoDeiRequisitiConfigurazionePrivata_v2_0_.pdf
  docs/assets/favicon/file-pdf.svg
  docs/index.md
  docs/pages/ArchivioDocumentiDeiRequisiti.md
  docs/pages/Documentazione Moduli/MMM-AirQuality/MMM-AirQuality.md
  docs/pages/Documentazione Moduli/MMM-Online-State/MMM-Online-State.md
  docs/pages/Documentazione Moduli/MMM-Screencast/MMM-Screencast.md
  docs/pages/Documentazione Moduli/MMM-ip/MMM-ip.md
  docs/pages/Documentazione Moduli/calendar/calendar.md
  docs/pages/Documentazione Moduli/clock/clock.md
  docs/pages/Documentazione Moduli/newsfeed/newsfeed.md
  docs/pages/Documentazione Moduli/weather/weather.md
  docs/pages/Documentazione Moduli/weatherforecast/weatherforecast.md
Labels: documentation, epic, new-feature

#181 #180 #157
  docs/pages/Documentazione Moduli/MMM-AirQuality/MMM-AirQuality.md
  docs/pages/Documentazione Moduli/MMM-Online-State/MMM-Online-State.md
  docs/pages/Documentazione Moduli/MMM-Screencast/MMM-Screencast.md
  docs/pages/Documentazione Moduli/MMM-ip/MMM-ip.md
  docs/pages/Documentazione Moduli/calendar/calendar.md
  docs/pages/Documentazione Moduli/clock/clock.md
  docs/pages/Documentazione Moduli/newsfeed/newsfeed.md
  docs/pages/Documentazione Moduli/weather/weather.md
  docs/pages/Documentazione Moduli/weatherforecast/weatherforecast.md
Labels: documentation, modify-feature, urgent
